config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'products#index'

  resources :products do
    resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :reviews
  validates :name, presence: true
  validates :cost, presence: true

  scope :usa_product, -> { where('country_of_origin =?', 'United States of America') }
  scope :three_latest_product, -> { order(created_at: :desc).limit(3) }

  scope :most_reviews, -> {
                         select('products.id, products.name, products.cost, count(reviews.id) as reviews_count')
                           .joins(:reviews)
                           .group('products.id')
                           .order('reviews_count DESC')
                           .limit(10)
                       }
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :product

  validates :author, :presence => true
  validates_length_of :content_body, minimum: 50, maximum: 250, too_short: 'is too short (minimum is 50 characters)', too_long: 'is too long (maximum is 250 characters)'
  validates :rating, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @usaproducts = Product.usa_product
    @latestproducts = Product.three_latest_product
    @mostreviews = Product.most_reviews
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Your sock is added to the list'
      redirect_to products_path
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:id])
    @reviews = @product.reviews
    render :display
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = 'Your sock is updated'
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    flash[:notice] = 'The sock is removed'
    redirect_to products_path
  end

private
  def product_params
    params.require(:product).permit(:name, :cost, :country_of_origin, :featured)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @product = Product.find(params[:product_id])
    @review = Review.new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = Review.new(review_params)
    @review.product_id = @product.id
    if @review.save
      flash[:notice] = 'Thank you for the review.'
      redirect_to product_path(@product.id)
    else
      render :new
    end
  end

private
  def review_params
    params.require(:review).permit(:author, :content_body, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<div class="panel">
  <% if object.errors.any? %>
    <h3>Oops, there's a hole in my sock.  Please fix these errors:</h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steve's Sock Shack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= f.label :name, "Sock name"%>
      <%= f.text_field :name %>
      <%= f.label :cost %>
      <%= f.text_field :cost %>
    </div>
    <div class="col-md-6">
      <%= f.label :country_of_origin, "Made in which country" %>
      <%= f.text_field :country_of_origin %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <%= f.label :featured, "Featured" %>
      <%= f.radio_button :featured, true %>
      <%= f.label :notfeatured, "Not Featured" %>
      <%= f.radio_button :featured, false %>
    </div>
    <div class="col-md-6">
  <%= f.submit "Add Sock"%>
    </div>
  </div>
</div>
<% end %>
<hr>

<h4><%= link_to "Go Home", products_path %></h4>

app/views/products/display.html.erb
<h3>Sock's name: <%= @product.name %></h3>
<p>Cost: $ <%= format('%.2f', @product.cost) %></p>
<p>Country of Origin: <%= @product.country_of_origin %></p>
<p>Featured Sock: <%= @product.featured %></p>
<p>Admin: <%= link_to "Edit Sock", edit_product_path(@product) %> | <%= link_to "Delete Sock", product_path, :data => {
      :confirm => "You sure?", :method => "delete"
    } %></p>
<hr>

<h3>Reviews</h3>
  <% if @product.reviews.any? %>
  <ul>
  <% @reviews.each do |review| %>
    <h5><%= review.author %></h5>
    <li><%= review.content_body %></li>
    <li><%= review.rating %> out of 5 socks</li>
    <br>
  <% end %>
  </ul>
  <% else %>
  <p>There are no reviews...yet!</p>
<% end %>
<h4><%= link_to "Add a Review", new_product_review_path(@product)  %></h4>
<hr>

<h4><%= link_to "Go Home", products_path %></h4>

app/views/products/edit.html.erb
<h1>Edit Sock</h1>

<%= render "form" %>

app/views/products/index.html.erb
<div class="container-fluid">
  <div class="jumbotron">
    <h1>Welcome to Steve's Sock Shack!</h1>
    <h2>In 2015, Steve Grundy fulfilled his dream creating an online store where people can express their feelings and creativity...through socks!</h2>
    <h2>The more stylish and sillier the sock, the better!</h2>
    <h3>"If your sock game is wack, go to Steve's Sock Shack!"</h3>
  </div>

  <h5>Admin: <%= link_to "Add a New Sock", new_product_path %></h5>
  <hr>

  <% if @mostreviews != nil %>
    <h3>Here are the TOP 10 reviewed socks! Check out the 'Sock Talk' in the links below! *</h3>
    <div class="container">
      <% @mostreviews.each do |product| %>
        <h4><%= link_to product.name, product_path(product) %>: $ <%= format('%.2f', product.cost) %> - <%= product.reviews.count %> 'Sock Talk' Reviews</h4>
      <% end %>
    </div>
  <% else %>
    <h4>The most reviewed socks are coming soon!</h4>
  <% end %>
  <h5>* per pair</h5>
  <hr>

  <% if @latestproducts != nil %>
    <h3>Fresh from our warehouse! The latest socks available... *</h3>
    <div class="container">
        <% @latestproducts.each do |product| %>
          <h4><%= link_to product.name, product_path(product) %>: $ <%= format('%.2f', product.cost) %></h4>
        <% end %>
    </div>
  <% else %>
    <h4>New socks are arriving soon!</h4>
  <% end %>
  <h5>* per pair</h5>
  <hr>

  <% if @usaproducts != nil %>
    <h3>Shop local! Here's a list of socks proudly made in the USA! *</h3>
    <div class="container">
      <% @usaproducts.each_slice(3) do |products| %>
        <div class="row">
          <% products.each do |product| %>
            <div class="col-md-4">
              <h4><%= link_to product.name, product_path(product) %>: $ <%= format('%.2f', product.cost) %></h4>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h4>No USA socks...yet</h4>
  <% end %>
  <h5>* per pair</h5>
  <hr>

  <% if @products != nil %>
   <h3>Here's a list of our available socks! *</h3>
    <div class="container">
      <% @products.each_slice(4) do |products| %>
        <div class="row">
          <% products.each do |product| %>
            <div class="col-md-3">
              <h4><%= link_to product.name, product_path(product) %>: $ <%= format('%.2f', product.cost) %></h4>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% else %>
    <h2>No socks...yet</h2>
  <% end %>
  <h5>* per pair</h5>
  <hr>
  
  <p>If your sock game is wack, go to Steve's Sock Shack!</p>
</div>

app/views/products/new.html.erb
<h1>Add a New Sock</h1>

<%= render "form" %>

app/views/reviews/_form.html.erb
<%= render "layouts/errors", :object => @review %>


<%= form_for [@product, @review] do |f| %>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= f.label :author %>
      <%= f.text_field :author %>
    </div>
    <div class="col-md-6">
      <%= f.label :content_body, "Review" %>
      <%= f.text_area :content_body, size: "50x5" %>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
    <%= f.label :rating %>
    <%= f.select :rating, [1, 2, 3, 4, 5] %>
    <br><br>
    <%= f.submit "Add Review"%>
    </div>
  </div>
</div>
<% end %>

<h4><%= link_to "Go Home", products_path %></h4>

app/views/reviews/new.html.erb
<h2>Add a new Review</h2>

<%= render 'form' %>